FROM photon:5.0

COPY ./make/photon/redis/redis-debuginfo-7.0.9-1.ph4.aarch64.rpm /redis/
COPY ./make/photon/redis/redis-7.0.9-1.ph4.aarch64.rpm /redis/

RUN tdnf install -y /redis/redis-debuginfo-7.0.9-1.ph4.aarch64.rpm /redis/redis-7.0.9-1.ph4.aarch64.rpm >> /dev/null \
    && rm -rf /redis \
    && tdnf clean all
